language: generic

sudo: false
dist: trusty

go:
  - 1.7

git:
  depth: 1

install:
  - gem install awesome_bot
  - go get github.com/russross/blackfriday
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/gorilla/mux

script:
  - awesome_bot README.md

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
