sudo: required
dist: trusty

language: go

go:
  - 1.4

before_script:
  - gem install awesome_bot

install:
  - go get github.com/russross/blackfriday
  - go get github.com/PuerkitoBio/goquery

script:
  - awesome_bot README.md

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
